
GET http://localhost:3000/api/offers/H7wbHN/comments HTTP/1.1

###

POST http://localhost:3000/api/offers/H7wbHN/comments HTTP/1.1
content-type: application/json

{
  "text": "Тестовый комментарий!"
}

###

DELETE http://localhost:3000/api/offers/H7wbHN/comments/InpFpV HTTP/1.1
